<a href="https://colab.research.google.com/github/Naeemah-Khatib/AI-Learning-Journey/blob/main/Day_6_Loops_%26_Automation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
for i in range(1, 6):
    print(i)

1
2
3
4
5

In [3]:
regions = ["NSW", "VIC", "QLD"]

for region in regions:
    print(region)

NSW
VIC
QLD

In [8]:
import requests as req

for user_id in range(1,6):
  resp = req.get(f"https://jsonplaceholder.typicode.com/users/{user_id}")
  print(resp.json()["name"])

Leanne Graham
Ervin Howell
Clementine Bauch
Patricia Lebsack
Chelsey Dietrich

In [15]:
import requests as req
import pandas as pd

users = []

for user_id in range(1,6):
  resp = req.get(f"https://jsonplaceholder.typicode.com/users/{user_id}")
  users.append(resp.json())

df = pd.DataFrame(users)
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [27]:
def get_multiple_users(start, end):

    users = []

    for user_id in range(start, end + 1):

        response = req.get(
            f"https://jsonplaceholder.typicode.com/users/{user_id}"
        )

        users.append(response.json())
        df = pd.DataFrame(users)
        df["City"] = df['address'].apply(lambda x: x['city'])
        df["Company"] = df['company'].apply(lambda x:x['name'])

    return df[['name','email','City','Company']]

df = get_multiple_users(1, 5)

print(df)

               name                      email           City  \
0     Leanne Graham          Sincere@april.biz    Gwenborough
1      Ervin Howell          Shanna@melissa.tv    Wisokyburgh
2  Clementine Bauch         Nathan@yesenia.net  McKenziehaven
3  Patricia Lebsack  Julianne.OConner@kory.org    South Elvis
4  Chelsey Dietrich   Lucio_Hettinger@annie.ca     Roscoeview

              Company
0     Romaguera-Crona
1        Deckow-Crist
2  Romaguera-Jacobson
3       Robel-Corkery
4         Keebler LLC

In [29]:
# More efficient
import requests
import pandas as pd

BASE_URL = "https://jsonplaceholder.typicode.com/users"

def get_multiple_users(start, end):

    users = []

    for user_id in range(start, end + 1):

        response = requests.get(f"{BASE_URL}/{user_id}")

        if response.status_code == 200:
            users.append(response.json())

    df = pd.DataFrame(users)

    df["City"] = df["address"].apply(lambda x: x["city"])
    df["Company"] = df["company"].apply(lambda x: x["name"])

    return df[["name", "email", "City", "Company"]]

users_df = get_multiple_users(1, 5)

print(users_df)

               name                      email           City  \
0     Leanne Graham          Sincere@april.biz    Gwenborough
1      Ervin Howell          Shanna@melissa.tv    Wisokyburgh
2  Clementine Bauch         Nathan@yesenia.net  McKenziehaven
3  Patricia Lebsack  Julianne.OConner@kory.org    South Elvis
4  Chelsey Dietrich   Lucio_Hettinger@annie.ca     Roscoeview

              Company
0     Romaguera-Crona
1        Deckow-Crist
2  Romaguera-Jacobson
3       Robel-Corkery
4         Keebler LLC

In [36]:
#just my testing
resp = req.get(BASE_URL).json()
users_list = []
users_list.append(resp[7])
users_list.append(resp[8])
df = pd.DataFrame(users_list)
df

,id,name,username,email,address,phone,website,company
0,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
1,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."

In [37]:
df = pd.DataFrame(resp)
user = df[df["id"] == 3]

print(user)

   id              name  username               email  \
2   3  Clementine Bauch  Samantha  Nathan@yesenia.net

                                             address           phone  \
2  {'street': 'Douglas Extension', 'suite': 'Suit...  1-463-123-4447

       website                                            company
2  ramiro.info  {'name': 'Romaguera-Jacobson', 'catchPhrase': ...